### ISSUE TITLE
gulp end event not firing in 2.0.0

### ISSUE THREAD

**Issue by stevejhiggs** [webdriverio/gulp-webdriver#41]
In v1.0.3 I use the gulp 'end' event to shutdown my selenium server:

``` js
return gulp.src('./wdio.conf.js'))
    .pipe(webdriver({
      wdioBin:  path.join(__dirname, 'node_modules', '.bin', wdioCommand)
    })).once('end', () => {
      selenium.child.kill();
    });`
```

however in 2.0.0 the 'end' event never fires. Is this intentional?

**Comment by christian-bromann** [comment]
@stevejhiggs yeah that was unfortunate implemented. I fixed it and published a new version `v2.0.1`

**Comment by azaslavsky** [comment]
Hi,
  I'm using 2.0.1, and I am still experiencing the error described above.  My code:

``` javascript
  gulp.src('wdio.conf.js')
      .pipe(wdio({
        host: 'localhost',
        port: 1234,
        logLevel: args.verbose ? 'verbose' : 'error',
        capabilities: capabilities
      }))
      .on('error', function(e) {
        //throw e;
      })
      .on('end', function() {
        console.log('I\'m finished!');
        if (!args.serverless) {
          servers.forEach(function(server) {
            server.kill();
          });
        }
        done();
      });
```

Any thoughts as to what I am doing wrong?

**Comment by christian-bromann** [comment]
Why can't you use the selenium-webdriver service? It seems that the end event is not propagated correctly

**Comment by azaslavsky** [comment]
I use appium for tests under certain configurations, so sometimes I need a plain old selenium server, whereas in other cases I need an appium server, or sometimes both.  I just run shells scripts to create my own as child processes as needed, then kill them once the test runner has done its thing.

Either way, the "end" event should be fired for a gulp plugin.

**Comment by azaslavsky** [comment]
Is there a workaround I could use in the meantime, something that will be able to pick up when the test suite is over at least?  If that were the case, I could kill the process myself.

**Comment by christian-bromann** [comment]
Let's continue the conversation in #47
